name: Build BOF Plugins

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y make mingw-w64 python3

    - name: Compile all plugins
      run: |
        # List of directories with Makefiles
        PLUGIN_DIRS=(
          "AD-BOF"
          "Creds-BOF"
          "Elevation-BOF"
          "Execution-BOF"
          "Injection-BOF"
          "Kerbeus-BOF"
          "LateralMovement-BOF"
          "Postex-BOF"
          "Process-BOF"
          "SAL-BOF"
          "SAR-BOF"
        )

        for dir in "${PLUGIN_DIRS[@]}"; do
          if [ -f "$dir/Makefile" ]; then
            echo "--- Compiling in $dir ---"
            (cd "$dir" && make)
            echo "--- Finished compiling in $dir ---"
            echo ""
          else
            echo "--- Makefile not found in $dir, skipping. ---"
          fi
        done

    - name: Commit and push compiled files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add --force . # Forcefully stage all new/modified files (including those in .gitignore)
        # Commit and push if there are changes
        if ! git diff --staged --quiet; then
          git commit -m "ci: Auto-compile and add BOF plugins"
          git push
        else
          echo "No new compiled files to commit."
        fi
